### ISSUE TITLE
Doesn't follow route_prefix changes in base config file

### ISSUE THREAD

**Issue by twoSeats** [Laravel-Backpack/Settings#10]
If one wishes to use a different `route_prefix` to 'admin' this package (& others) break uniformity since they are hard coded to make use of the 'admin' prefix.

This can be improved by causing them to use the config value of a published config file, & defaulting to 'admin' if there isn't a config value set.

I'm working on this.
Will be done in 1 day.

**Comment by tabacitu** [comment]
That. Would. Be. GREAT!!
Thank you!

Let's leave this issue open until then.

Cheers!
