### ISSUE TITLE
Using table field cause ViewException in latest version (Probably have something to do with Backpack 4.1)

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/Settings#102]
# Bug report

### What I did:
Use table field

### What I expected to happen:
Show table field in update route

### What happened:
Here's the stack trace
https://flareapp.io/share/NPGJqOmG#F85

### What I've already tried to fix it:
Nothing. Tried to debug it but can't find anything

### PHP VERSION:
PHP 7.3.12 (cli) (built: Nov 19 2019 13:58:02) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v7.12.0@c2fff1e9879494a6f853593b3c517dc9922bbb51

### BACKPACK VERSION:
4.1.6@cbd4143d3eb8302916012af205565cd3183f274f

**Comment by tabacitu** [comment]
@drionix did you get to the bottom of this? I couldn't receive the same error myself - maybe you can share your addField() call so we test with the same thing?

Cheers!

**Comment by tabacitu** [comment]
Ps. Excellent thing - sharing the stack trace using Flare App. Excellent!

**Comment by pxpm** [comment]
Hello @drionix 

I think you have an outdate version of wrapper_start.blade.php. 

I can spot one of the differences here: 
` $field['wrapper'][$attributeKey] = !is_string($value) && is_callable($value) ? $value($crud, $field, $entry ?? null) : $value ?? '';`

Line 7 of your provided error.

**Comment by drionix** [comment]
> Hello @drionix
> 
> I think you have an outdate version of wrapper_start.blade.php.
> 
> I can spot one of the differences here:
> ` $field['wrapper'][$attributeKey] = !is_string($value) && is_callable($value) ? $value($crud, $field, $entry ?? null) : $value ?? '';`
> 
> Line 7 of your provided error.

@pxpm Oh wow! That's exactly the problem! Thanks a lot for noticing. Can't express my gratitude with words.

I browse around a little bit and found out that this bug was apparently fixed in Backpack version 4.1.7 with Laravel-Backpack/CRUD#2862 while my current version is 4.1.6. However, there's no documentation concerning this version incompatibility.

This means that it is more of a Laravel-Backpack/CRUD bug rather than Laravel-Backpack/Settings'.
