### ISSUE TITLE
MongoDB compatibility

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/Settings#106]
# Bug report

### What I did:

Tried to install this package in MongoDB.

### What I expected to happen:

The package to be installed.

### What happened:

Error in ServiceProvider. https://github.com/Laravel-Backpack/Settings/blob/f0f0051d8d91f9601e334fc6ca0bf1b9df666eac/src/SettingsServiceProvider.php#L39

`Schema::getColumnListing()` is not compatible with non-sql databases.

**Comment by promatik** [comment]
@pxpm This is only counting the columns on settings table to check if it exists.

```php
// only use the Settings package if the Settings table is present in the database
if (!\App::runningInConsole() && count(Schema::getColumnListing('settings'))) {
```

Can we use `Schema::hasTable('settings')` there?
Don't know if it's compatible with mongodb, since it uses collections instead of tables, but it's more likely.

**Comment by promatik** [comment]
Moving to #119 ✌
