### ISSUE TITLE
type checkbox is not working shows wyswyg

### ISSUE THREAD

**Issue by hardikdangar** [Laravel-Backpack/Settings#110]
# Bug report

### What I did:

In settings table i have added setting with following values,
`{"name":"value","label":"Suppress Topic","type":"checkbox"}`
It shows up in /admin/settings as well.
see https://i.imgur.com/dMuVwJV.png

### What I expected to happen:

I expected edit setting page to open with checkbox.

### What happened:

Instead it opens with wyswyg editor. see https://i.imgur.com/rj65Ba0.png

### What I've already tried to fix it:

I tried to debug the issue but there is nothing i could find that could cause this.

### Backpack, Laravel, PHP, DB version:

Laravel = 7.29.3
Backpack = 4.1.10
backpack/settings = 3.0.7

Is this bug or i am missing something from documentation?

**Comment by pxpm** [comment]
Hello @hardikdangar 

All settings `name` is `value` ?

**Comment by hardikdangar** [comment]
i tried to change name of all three entries that also didn't help.

**Comment by hardikdangar** [comment]
It seems issue was with SettingCrudController. I have fixed it. i had copied SettingCrudController from old backpack version and i needed to copy the new one with new version.
