### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by exussum12** [Laravel-Backpack/Settings#115]
The licencing on this is confusing

The ![Licence File](https://github.com/Laravel-Backpack/Settings/blob/master/LICENSE.md) suggests YUMMY
The ![Readme](https://github.com/Laravel-Backpack/Settings/blob/master/README.md) suggests MIT 
![image](https://user-images.githubusercontent.com/1102850/116845121-db940d80-abdc-11eb-91c5-16006273ff65.png)

![Composer](https://github.com/Laravel-Backpack/Settings/blob/master/composer.json#L16) suggests Propriety - Could these be all aligned to the preferred licence ?

**Comment by tabacitu** [comment]
Right! Thank you @exussum12 - I've just removed the MIT license mentioned in the README. It hasn't been under MIT in a long time.

Cheers!

**Comment by tabacitu** [comment]
@promatik could you please do the same as https://github.com/Laravel-Backpack/Settings/commit/fe3594c3862e0e275313e4ef1bc5d40a1550f7ab for our other packages?
