### ISSUE TITLE
Multi language support for field edit.

### ISSUE THREAD

**Issue by kee0624** [Laravel-Backpack/Settings#117]
Hi, may I know how to make the settings field support multi-language? Similarly like article/category.

**Comment by promatik** [comment]
Hi @kee0624!

Right now `Settings` doesn't support to have some translatable values.
It is possible to do it for your project, you'll need to replace the current Controller and the current Model.

You can replace Backpack `SettingCrudController` by doing a bind;

```php
// service provider
public function boot()
{
    $this->app->bind(
        \Backpack\Settings\app\Http\Controllers\SettingCrudController::class, 
        \App\Http\Controllers\SettingCrudController::class
    );
}
```

Then you'll need to define your Settings Model in the overriden controller, something like this;
_(please note this code may have bugs, it's not tested)_

```php
namespace App\Http\Controllers;

class SettingCrudController extends \Backpack\Settings\app\Http\Controllers\SettingCrudController
{
    public function setup()
    {
        parent::setup();

        CRUD::setModel(\App\Models\Setting::class);
    }
}
```

Then on your Model you can set `use HasTranslations` and set `$translatable = ['value']`.
Note that this will make value translatable for all the keys.

@kee0624 for now I'll close this issue, but if you have any doubt about this, feel free to to ask ✌

**Comment by tabacitu** [comment]
Hey - just wanted to jump in to say we have no plans to make this package support multi-language settings. 
So if anybody needs that, they should roll their own. 

One way is what @promatik suggested above. 
Another way would be to copy everything from this package into their own project, replace the namespaces, and modify to their liking.

Each with his own 😀

Cheers!
