### ISSUE TITLE
Is there a reason you don't allow this to run in CLI mode?

### ISSUE THREAD

**Issue by hhhc** [Laravel-Backpack/Settings#126]
# Bug report
We need some of the settings already in CLI mode but the ServiceProvider actively prohibits that. Is there a reason for this?

**Comment by maurohmartinez** [comment]
Hi @hhhc!

Yes, there is a reason... The reason is that the package performs a db query every time the app is booted to merge the db settings with Laravel config provider. If we allow that to run in cli, a php artisan any-command would be doing that check.

Cheers!
