### ISSUE TITLE
Why would an error?

### ISSUE THREAD

**Issue by eleven0220** [Laravel-Backpack/Settings#13]
run:  php artisan vendor:publish --provider="Backpack\Settings\SettingsServiceProvider"

[League\Flysystem\FileNotFoundException]
  File not found at path: 015_08_04_131614_create_settings_table.php

**Comment by tabacitu** [comment]
@eleven0220 , that's very odd. I just tried, it works for me as expected. Are you sure you haven't modified something in /vendor/ that messes things up? Maybe renamed the migration file?

Cheers!

**Comment by eleven0220** [comment]
I didn't do any modification
