### ISSUE TITLE
How is supposed to work with a select field?

### ISSUE THREAD

**Issue by Deca** [Laravel-Backpack/Settings#131]
### What I did:
Trying to add a select field defining also the values, this is the code used

```{"name": "value","label": "point type","type": "select_from_array","options": {"fixed":"Fixed","adaptive":"Adaptive"},"allows_null": false,"default": [],"allows_multiple": false}```

### What happened:
When I try to load the edit page of that specific setting I get this error
```Trying to access array offset on value of type null```

 
### Backpack, Laravel, PHP, DB version:
Backpack 4.1.71
Laravel 8.83.27
php 8.2.3

**Comment by jcastroa87** [comment]
Hello @Deca 

You can follow instructions on our [docs](https://backpackforlaravel.com/docs/6.x/crud-fields#select_from_array) or can check our [demo](https://github.com/Laravel-Backpack/demo/blob/main/app/Http/Controllers/Admin/MonsterCrudController.php) too.

```
CRUD::field([ 
    'name'              => 'value',
    'label'             => 'point type',
    'type'              => 'select_from_array',
    'options'           => ['fixed' => 'Fixed', 'adaptive' => 'Adaptive'],
    'allows_null'       => false,
    'allows_multiple'   => false,
]);
```

Cheers.

**Comment by Deca** [comment]
Thanks @jcastroa87 I missed that demo example in the doc, that clarifies a lot of doubts about field types configuration!

**Comment by jcastroa87** [comment]
Your welcome :)

I will close the issue, but please feel free to reopen or create new one if it needed.

Cheers
