### ISSUE TITLE
Having issue with images

### ISSUE THREAD

**Issue by joshwegener** [Laravel-Backpack/Settings#137]
# Bug report

### What I did:
Created the following setting in the seeder:

        [
            'key'         => 'site_background_image',
            'name'        => 'Background Image',
            'description' => 'The background image of the site',
            'value'       => '',
            'field'       => '{"name":"background_image","label":"Background Image","type":"image","crop":true,"aspect_ratio":0,"withFiles":true,"hint":"The background image of the site"}',
            'active'      => 1,
        ],

### What I expected to happen:
Select an image to display as the background image

### What happened:
After I selected the image in the admin panel, I received an error
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'background_image' in 'field list'`
Stack trace here: https://flareapp.io/share/v5pbyQMP

### What I've already tried to fix it:
I have no idea what I'm doing

### Backpack, Laravel, PHP, DB version:
Backpack 6.6
Laravel 10.10
PHP 8.3.3
MySql 8.0.36

**Comment by karandatwani92** [comment]
Hey @joshwegener 

Try the following. It works for my website:
```json
{
 "name": "value",
 "label": "Value",
 "type": "image",
 "crop": true,
 "hint": "Best Fit: 1920x400",
 "aspect_ratio": 4.8,
 "withFiles": 
 {
 "disk": "public",
 "path": "destination"
 }
}
```

Remember, Settings CRUD stores the values only in `value` field.
