### ISSUE TITLE
Suggestion/question about addon

### ISSUE THREAD

**Issue by craftenergy22** [Laravel-Backpack/Settings#138]
Hello! Is it possible to present the list of settings as a single form in order to edit the necessary settings in one place, rather than through a list and editing one of the settings?

![123](https://github.com/Laravel-Backpack/Settings/assets/123014863/b34903e9-ef3c-4169-951b-917919277243)

**Comment by karandatwani92** [comment]
Hey @craftenergy22

Setting CRUD is not planned the way you want to set it up. If you still want something similar, here is a workaround(not recommended):

Create one Repeatable Field with fixed fields & rows:
```json
{
  "name": "value",
  "label": "Value",
  "type": "repeatable",
  "subfields": [
    {
      "name": "something1"
    },
    {
      "name": "something2"
    }
  ],
  "init_rows": 1,
  "min_rows": 1,
  "max_rows": 1
}
```
