### ISSUE TITLE
Maximum field length for a setting value

### ISSUE THREAD

**Issue by easydevgit** [Laravel-Backpack/Settings#139]
how can I set the maximum field length for a setting value on the settings list page. To avoid displaying too much text if the setting value is long text

**Comment by munjaldevelopment** [comment]
@easydevgit Please share screenshot for more details as this is not clear..

**Comment by easydevgit** [comment]
![Ashampoo_Snap_вторник, 4 июня 2024 г _13h41m30s_002_Laravel-BackpackSettings Application settings interface for Backpack (for Laravel 6)  � Brave](https://github.com/Laravel-Backpack/Settings/assets/97016851/87cd0561-b89e-4d84-a116-cc56c5b074d2)

**Comment by easydevgit** [comment]
maximum text length showing here

**Comment by pxpm** [comment]
@easydevgit in your column definition add: `'limit' => 20` (for 20 character limit for example).

**Comment by easydevgit** [comment]
Thank you
