### ISSUE TITLE
SettingsTableSeeder problem

### ISSUE THREAD

**Issue by frankar** [Laravel-Backpack/Settings#14]
on https://github.com/Laravel-Backpack/Settings/blob/master/src/database/seeds/SettingsTableSeeder.php
on line 51

'field'         => '{"name":"value","label":"Value", "title":"Motto value" ,"type":"textarea"}',

must be 

'field'         => '{"name":"value","label":"Value","type":"textarea"}',

Setting title attribute, if I change "label":"Value" in "label":"My Value" it don't work

**Comment by tabacitu** [comment]
Hi @frankar ,

Just checked, for me it works as it is:
![screen shot 2016-11-06 at 20 08 09](https://cloud.githubusercontent.com/assets/1032474/20040274/cf91a416-a45c-11e6-889a-c83ea72f3426.png)
Also made the change you mentioned from Value to My Value and that works too.

1) What database are you using? MySQL? PosgreSQL? SQLite? SQL Server?
2) Are you sure your database GUI doesn't insert escape characters in JSON when you save? That would explain your second problem.

Cheers!

**Comment by frankar** [comment]
In your screenshot I see "Value" displayed, not "My Value".
I use MySql on my MacBook. My database gui is "Sequel Pro", no any escape char.
I think the problem is only that textarea field not as title attribute.

**Comment by tabacitu** [comment]
You're right - now I understand. Changed it, thank you!
