### ISSUE TITLE
Nothing to publish for tag [] and Table 'xxxxxx.settings' doesn't exist

### ISSUE THREAD

**Issue by BinaryBlock** [Laravel-Backpack/Settings#21]
Hey,

I'm not sure what the ultimate issue is, but I can tell you what happened and what I did to fix it.

I am running Laravel 5.3 and tried to add backpack/settings. I followed the steps in README and it kept blowing up when I tried to execute the line:
`php artisan db:seed --class="Backpack\Settings\database\seeds\SettingsTableSeeder"`
I would get the error:
```
 [Illuminate\Database\QueryException]                                                                                                     
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxx.settings' doesn't exist (SQL: insert into `settings` (`key`, `na  
  me`, `description`, `value`, `field`, `active`) values (contact_email, Contact form email address, The email address that all emails fr  
  om the contact form will go to., admin@updivision.com, {"name":"value","label":"Value","type":"email"}, 1))      
```
Yes, I did all the step in order AND added `Backpack\Settings\SettingsServiceProvider::class,` to my `config/app.php file`.

For the life of me I couldn't tell why the command `php artisan migrate` was not creating the table. I tried all kinds of other commands to clear the cache (in case that was the problem):
`php artisan config:clear`
`php artisan cache:clear`

Finally, I looked at the Laravel 5.3 documentation for Package Development : Package Migrations
https://laravel.com/docs/5.3/packages#migrations

I added the following like to this file at line 28: https://github.com/Laravel-Backpack/Settings/blob/master/src/SettingsServiceProvider.php#L28

`$this->loadMigrationsFrom(__DIR__.'/database/migrations');`

The I re-ran the following commands and it worked:
`php artisan vendor:publish --provider="Backpack\Settings\SettingsServiceProvider"`
`php artisan migrate`
`php artisan db:seed --class="Backpack\Settings\database\seeds\SettingsTableSeeder"`

Hope that helps! Also, hope someone knows what went wrong. Was it a Laravel 5.3 thing?

Thanks,
@binaryblock

**Comment by daghaner** [comment]
i did try it.. unfortunately same error still!

**Comment by tabacitu** [comment]
Hmm... @BinaryBlock , I think I understand and have a solution for it [here](https://github.com/Laravel-Backpack/Settings/pull/19) (at the end of the thread).

Thanks, cheers!
