### ISSUE TITLE
Unable to edit using user interface

### ISSUE THREAD

**Issue by madd86** [Laravel-Backpack/Settings#22]
**Problem**

On settings interface I click on the 'edit' button of the row I wanna edit. I add the text and click save, doesn't save.

**This is what my DB looks like**

![This is what my DB looks like](https://cloud.githubusercontent.com/assets/23120598/21590435/deddb164-d0e2-11e6-8e85-5f19e5d80f1e.PNG)

If I add a value there, and then go to the user interface, I see that value on the **list** view, but not on the **form** view.

**Comment by madd86** [comment]
Found the problem

Name has to be **value**. Either that wasn't clear enough or I didn't check carefully enough, either way you guys need to add an example of the json and specify name should always be **value**.

I can help write the documentation.

**Also, another problem I seem to be having**:

Text doesn't work for string only integers for some reason. Textarea works for everything.

**Comment by OwenMelbz** [comment]
Hi, not sure what you mean regards to "name has to be value" the name field should just be used as a label for the field.

Eg. Support Email Address

**Comment by madd86** [comment]
Say I have this:

`{"name":"value","label":"Email", "title":"Email" ,"type":"textarea"}`

The above json works.

Then I go ahead and change it to this:

`{"name":"email","label":"Email", "title":"Email" ,"type":"textarea"}`

It stops working. That's what I mean.

**Comment by OwenMelbz** [comment]
what about ?

`{"label":"Email", "title":"Email" ,"type":"textarea"}`

**Comment by madd86** [comment]
Cool, that does work too, but this is what is stated on the mini-doc: 

> field (Backpack CRUD field configuration in JSON format. https://laravel-backpack.readme.io/docs/crud-fields#standard-field-types)

What's the conclusion I jump into? _That's easy, all I have to do is get the array and convert it to json._ 

So what do I do? Get the array and convert it to json. And what does the array contain? Name.

Maybe put an example there to make things easier.

Thanks anyway, I wanna help in anyway I can and sometimes the documentation can seem a bit lacking here and there. Having tried other admin/crud packages, this is by far the best one.

**Comment by OwenMelbz** [comment]
Sure :) you can always submit your own Pull Requests and Suggest Edits to the documentation via the websites if you spot issues, then they can be reviewed and applied where applicable.

**Comment by cmarfil** [comment]
Same here, i think that It's very rare that you have to guess that the name must be "value" or not exist, the example of the documentation is not correct.
