### ISSUE TITLE
How to use select or "page_or_link"

### ISSUE THREAD

**Issue by lotarbo** [Laravel-Backpack/Settings#24]
Hi, i need store in settings select, where i can select some model, i try use page_or_link
but have an error
```
ErrorException in Fields.php line 28:
Undefined index: name
```

my json
`{"name":"value","label":"Name" ,"type":"page_or_link", "page_model":"App\Models\Event"}`

**Comment by lotarbo** [comment]
Sorry, my bad, need escape \
`{"name":"value","label":"Name" ,"type":"page_or_link", "page_model":"App\\Models\\Event"}`
with this json all work.
But mb u have a better choice for this? cos I need only select model

**Comment by antonino-ferreira** [comment]
You could create a custom field for that!

Create a blade file 'resources/views/vendor/backpack/crud/fields/select_event.blade.php':

```blade
<div @include('crud::inc.field_wrapper_attributes') >
    <label>{!! $field['label'] !!}</label>
    <?php $events = App\Models\Event::all(); // Or the desired method in the Model… ?>
    <select class="form-control" name="{{ $field['name'] }}">
        @if (!count($events))
            <option value="">-</option>
        @else
            @foreach ($events as $key => $event)
                <option value="{{ $event->id }}"
                    @if ( old($field['name']) == $event->id)
                         selected
                    @endif
                >{{ $event->name }}</option>
            @endforeach
        @endif
    </select>
</div>
```

And then in the Seeder just add to the field:
{"name":"value","label":"Name" ,"type":"select_event"}
