### ISSUE TITLE
Laravel 5.4 : The setting value returns null value on console command

### ISSUE THREAD

**Issue by adarmanto** [Laravel-Backpack/Settings#25]
As described on title, I can not get the value from my console command class, but it works on Controller class or other places.

**Comment by OwenMelbz** [comment]
Use the search search search search search :) https://github.com/Laravel-Backpack/Settings/issues/23

**Comment by adarmanto** [comment]
aah, sorry! I did search though before posting, but I searched it on open issues only :-) Thank you!
