### ISSUE TITLE
Button title

### ISSUE THREAD

**Issue by packytagliaferro** [Laravel-Backpack/Settings#28]
After install the "save" buttons have all changed to `backpack::crud.save_action_save_and_back`
![Uploading Screen Shot 2017-03-09 at 6.48.48 PM.png…]()

**Comment by tabacitu** [comment]
Hi @packytagliaferro ,

If you've just upgraded from Backpack\CRUD 3.1 to 3.2, you need to republish your translation files. Please [follow all steps in the upgrade guide](https://laravel-backpack.readme.io/v3.0/docs/upgrade-from-31-to-32#section-how-to-upgrade). Step 3 is the one you're missing, I think.

Cheers!
