### ISSUE TITLE
[Bug] Settings module gives you the option to "save and create new" when you can't create new settings

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/Settings#30]
![image](https://cloud.githubusercontent.com/assets/7759267/24837364/4efddac4-1d3b-11e7-831a-64a994fd7a1f.png)

i guess you should remove this option here

**Comment by OwenMelbz** [comment]
I'm confused lol, what's he problem? I only speak/read English haha

**Comment by AurelDragut** [comment]
you cant add new settings by the option, its not made this way :)

**Comment by OwenMelbz** [comment]
Oh right I see lol will need to have a think about making some sort of API for it then, or at least documenting a way

**Comment by AurelDragut** [comment]
I didnt say it should have the option to add new settings :) also @tabacitu made it clear that adding settings should not be an option available to any admin or user, and i kinda agree with him. That is only for developers to do, so this is why i said that the "add new" line should be removed.

**Comment by lloy0076** [comment]
@AurelDragut - is this still an issue? Does the `add new` button work?

**Comment by AurelDragut** [comment]
I don't know, i haven't used settings for quite a while. Should be checked.

**Comment by OwenMelbz** [comment]
I imagine this still exists, more of a user Journey bug than functionality, but deffo worth investigating, shouldn't be too bad tonfix

**Comment by tabacitu** [comment]
This has been fixed directly in Backpack\CRUD - if CREATE is denied (like it is here), that button will no longer show up:

![screen shot 2018-10-15 at 11 03 55](https://user-images.githubusercontent.com/1032474/46937496-1effee00-d06a-11e8-995e-e551eb988504.png)

So... fixed! :-)

Thanks, cheers!
