### ISSUE TITLE
Multiple fields per row

### ISSUE THREAD

**Issue by techpoints** [Laravel-Backpack/Settings#32]
## How can this be done? 

![capture](https://cloud.githubusercontent.com/assets/11186278/25773360/bc0faae4-3284-11e7-8c27-476aad823246.PNG)

![captu4re](https://cloud.githubusercontent.com/assets/11186278/25773401/88338fbe-3285-11e7-975f-d08801a0b8e3.PNG)

**Comment by tabacitu** [comment]
Hi @techpoints ,

We don't have that built-in.

But you can extend/customize anything that backpack doesn't provide. In this case, I recommend you [create a custom field type](https://laravel-backpack.readme.io/docs/crud-fields#section-custom-field-types) for your need. Say... ```width_and_height.blade.php```, starting from the ```number``` field, that includes the two fields you need.

Hope it helps.

Cheers!
