### ISSUE TITLE
Number Field attributes problem

### ISSUE THREAD

**Issue by F4bsi** [Laravel-Backpack/Settings#33]
Hey,

I have a problem with the number field.
If I try to add attributes for the step or min / max number  like this:
`{"name":"value","label":"Value", "title":"Zoom Stufe" ,"type":"number", "attributes":{"min":"10", "max":"20"}}`
And try to edit the settings for that it throws the error:
**Cannot use object of type stdClass as array**

If I change the json_decode parameter in the SettingCrudController to true like this: `  $this->crud->addField((array) json_decode($this->data['entry']->field), true);` it works, but I'm not quite sure if it is a good solution or if the problem is, that my json was wrong... Any suggestions?

**Comment by lloy0076** [comment]
I think this is an enhancement with a short(ish) sort of PR.

**Comment by adriandmitroca** [comment]
This has been fixed here: https://github.com/Laravel-Backpack/Settings/pull/69

**Comment by tabacitu** [comment]
Merged and tagged. Thank you @adriandmitroca !
