### ISSUE TITLE
No data when I'm trying to access from console command.

### ISSUE THREAD

**Issue by deepslam** [Laravel-Backpack/Settings#34]
Hello!
Thank you for the great project but apparently, I've found the bug:

I'm trying to create console command and code such as

`echo Config::get('settings.contact_email');`

Returns empty string.
But if I'm trying to access to the same code from frontend it's all working perfect.
Am I doings something wrong or it's the bug?

Sincerely, Dmitry

**Comment by tabacitu** [comment]
Hi @deepslam ,

How about if you change the order of your service providers in your ```config/app.php```?  

First ```        Backpack\Settings\SettingsServiceProvider::class```,
then ```        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class```

Does this fix it for you?

**Comment by moustacherepublic** [comment]
Hi there, 

I met the same issue when using Laravel queue.
The supervisord calls the 'php artisan' command actually which would fail to fulfill the condition in class \Backpack\Settings\SettingsServiceProvider :
```
if (!\App::runningInConsole() && count(Schema::getColumnListing('settings'))) {
...
```

Could you please fix this issue ?

Thanks,
Skyler

**Comment by tabacitu** [comment]
Hi @moustacherepublic ,

Unfortunately, there's a reason for ```!\App::runningInConsole()``` to be there: https://github.com/Laravel-Backpack/Settings/pull/19

A temporary solution for you would be to use the model inside your console commands, to get the info. So:
```
\Backpack\Settings\app\Models\Setting::where('key', 'settings.contact_email')->first()->value
```
should be the same as
```
Config::get('settings.contact_email')
```

This is probably the way we'll pluck the settings in the future anyway, using a ```setting()``` helper, to prevent this conflict.

**Comment by InkedCurtis** [comment]
Any update for support on this?

**Comment by tabacitu** [comment]
@InkedCurtis just created a PR that provides support for this - https://github.com/Laravel-Backpack/Settings/pull/70

Will probably be merged later today.
