### ISSUE TITLE
Working fine with mysql but fail on postgreSQL

### ISSUE THREAD

**Issue by pacobabs** [Laravel-Backpack/Settings#5]
Hi, first want to thank you for these very useful packages but I get errors when working with a postgreSQL database. 
Here when I try to install the migration files for the settings package I got this error.

`SQLSTATE[42601]: Syntax error: 7 ERREUR:  syntax error near LIKE 
LINE 1: SHOW TABLES LIKE 'settings'                                                 
                    ^ (SQL: SHOW TABLES LIKE 'settings')                            `

But with MySQL everything is working fine.

**Comment by tabacitu** [comment]
Hi @ pacobabs,

The Backpack packages have NOT been tested with postgreSQL. There are a few know issues, but not this one, thank you.

There is a pretty simple solution, http://stackoverflow.com/questions/25368382/show-tables-like-in-postgresql for SettingServiceProvider:28, but there should be a better, more general way to do this rather than just checking the database type and running a different command for mysql and postgre.

Any ideas?

**Comment by ngutip** [comment]
i use sqlite, so i change the myqsl specific "show table" to PDO 
edit file /vendor/backpack/settings/src/SettingsServiceProvider.php in line 30

`if (count(Schema::getColumnListing('settings'))) { ....`

then add

` use Illuminate\Support\Facades\Schema;`

then command 

`php artisan optimize`

hope will fix this issue

**Comment by ngutip** [comment]
you will have to change line DB::raw('SHOW COLUMNS FROM in
/vendor/backpack/crud/src/PanelTraits/AutoSet.php and /vendor/backpack/crud/src/CrudTrait.php with 
`Schema::hasColumn( string $table, string $column)`
all shema method please refer to documentation [/Illuminate/Database/Schema/Builder](https://laravel.com/api/5.2/Illuminate/Database/Schema/Builder.html)

**Comment by pacobabs** [comment]
Hi all and thanks for your answers. @ngutip @tabacitu . Many packages of the Laravel Backpack are working fine with PostgreSQL. I don't need too much the settings package in the project I am working at this time, just wanted to contribute and hope there will be a version fully tested with postgreSQL. Good job.

**Comment by mmontone** [comment]
I'm having the same problem with Posgres. I wish this could be fixed.

**Comment by mmontone** [comment]
Also, for the future, I think it would be good to prefix backpack tables. 'backpack_settings' instead of 'settings', to avoid name clashes with an existing application.

**Comment by tabacitu** [comment]
Thank you, @ngutip . I've implemented your solution.
@mmontone , could you please confirm it's working for you now?

Cheers!

**Comment by tabacitu** [comment]
(after a ```composer update```)

**Comment by pacobabs** [comment]
Hi all, @mmontone for postgres i've updated this file based on @ngutip suggestions.
**/vendor/backpack/crud/src/PanelTraits/AutoSet.php**
`  public function getDbColumnTypes(){
        foreach (\DB::select(\DB::raw("SELECT column_name as Field,data_type as Type,column_default as Default FROM information_schema.columns WHERE table_name = '".$this->model->getTable()."'")) as $column) {
            $this->field_types[$column->field] = ['type' => trim(preg_replace('/\(\d+\)(.*)/i', '', $column->type)), 'default' => $column->default];
        }
        return $this->field_types;
    }`

Hope this will help.
