### ISSUE TITLE
Package migrations and seeds should be publishable

### ISSUE THREAD

**Issue by PortStone** [Laravel-Backpack/Settings#50]
When developing and using, for example, something like `php artisan migrate:refresh --seed` the migrations and seeds for settings are not getting migrated again.

**Comment by tabacitu** [comment]
The migrations are published, but the seeds are not, indeed. I don't think the seeds should be published, since it's just demo stuff. So I'll close the issue.

I could be wrong, of course. Let me know if so :-) It's been known to happen.

Cheers!
