### ISSUE TITLE
Change default admin route prefix issue

### ISSUE THREAD

**Issue by bahman2216** [Laravel-Backpack/Settings#63]
# Bug report
In 

> SettingServiceProvider.php 
setupRoutes method

I changed
### What I did:
`            Route::group(['prefix' => config('backpack.base.route_prefix', 'admin'), 'middleware' => ['web', 'admin']], function () {
                // Settings
                Route::resource('setting', 'SettingCrudController');
            });
`
Also in 

> SetingCrudController.php line 18
`$this->crud->setRoute(config('backpack.base.route_prefix', 'admin').'/setting');`

### What happened:
404 not found if I change default prefix admin route
Also same error in file manager.

**Comment by tabacitu** [comment]
Hi @bahman2216 ,

Sounds to me like you're using an old Backpack\Settings version. New versions have the route in a separate file, that you can easily overwrite. Can you please confirm that doing a ```composer update``` eliminates this issue?

Thanks, cheers!

**Comment by bahman2216** [comment]
Yes, fixed. Thanks
