### ISSUE TITLE
[Bug] Doesn't work with non-default guard

### ISSUE THREAD

**Issue by chescos** [Laravel-Backpack/Settings#76]
# Bug report

### What I did:

Used separate auth guards for the admin panel and website.

### What I expected to happen:

That I could still update Settings with this addon.

### What happened:

I got a "403 Forbidden" error when trying to update a setting. That's because the `authorize` method in `src/app/Http/Requests/SettingRequest.php` only checks the default guard. It should check for the guard that is specified in `config/backpack/base.php`.

### What I've already tried to fix it:

-

### Backpack, Laravel, PHP, DB version:

-

**Comment by tabacitu** [comment]
You're totally right @chescos - thank you. Just merged @ShamarKellman 's PR which fixes this, so a ```composer update``` should fix it for you.

Thanks again for reporting this. Cheers!
