### ISSUE TITLE
Error when using MongoDB

### ISSUE THREAD

**Issue by elfeffe** [Laravel-Backpack/Settings#8]
If you try to `composer require backpack/settings` and you have MongoDB as default DB, you get this error

> PHP Fatal error:  Call to a member function prepare() on null in /Users/Dev/laravel/backpack/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 333

I think it's related to this:
https://github.com/jenssegers/laravel-mongodb/issues/888

**Comment by tabacitu** [comment]
Hi!

Sorry, the packages have not been tested AT ALL with mongodb. It's on the roadmap, but only in a few months... They currently support MySQL and PostgreSQL (with a known minor issue in postgre that will be fixed shortly).

If, however, you need MongoDB and are willing to do the fixes yourself until then, I'll be more than happy to merge your pull requests... There should't be that many issues though, they use eloquent in 99% of the cases...

**Comment by elfeffe** [comment]
I will try :)
Any plan to add user management with roles? This is the missing package, no?

**Comment by elfeffe** [comment]
No, you have it https://github.com/Laravel-Backpack/PermissionManager

**Comment by tabacitu** [comment]
Actually, user management with roles is already done, in Backpack/PermissionManager - https://github.com/Laravel-Backpack/PermissionManager

It works like this:
- a user can have multiple roles
- a role can have multiple permissions
- a user can receive extra permissions, in addition to the ones on his roles

Cheers!

**Comment by tabacitu** [comment]
Sorry, just seen your second comment :-)

**Comment by tabacitu** [comment]
@elfeffe , any info on using Backpack with MongoDB? Still using it? Any other issues?

Cheers!

**Comment by elfeffe** [comment]
I'm just using MongoDB for my custom tables, and MySQL for normal Laravel task, because most of Laravel components works better with MySQL.
So, Backpack doesn't work with MongoDB and I have no time (and mostly knowledge) to make it compatible.
But I'm using them together with my custom tables

**Comment by tabacitu** [comment]
Oh, ok. I understand :-) Not a MongoDB user myself, so I guess we won't offer support until someone offers to contribute with that.

Ok, thanks, cheers!
