### ISSUE TITLE
Override existing configurations

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/Settings#83]
just like its mentioned on the readme.. I tried the skin config but nothing happens.

ive added the AppServiceProvider code as well.. but nothing happens and when i try to call the Setting facade directly to \config\backpack.base, it throws an error.

how can we set config values directly from the db?

**Comment by tabacitu** [comment]
Hi @mpixelz , this looks like it doesn't belong here. This is the repo for the Settings package, not Base.

You can't set a config from the db in Laravel. The configs are loaded before the database. But you can create a Service Provider or something like that, that after the database is loaded, overwrites the config values with whatever is in the database (```Config::set('backpack.base.skin', $dbValue);```). Hope it helps you get started.

Cheers!
