### ISSUE TITLE
extending SettingCrudController

### ISSUE THREAD

**Issue by 3Flag** [Laravel-Backpack/Settings#84]
# Bug report

### What I did: 
Extend SettingCrudController and implementing my own Setting Store and Update request as UserSettingRequest. I'm trying to implement a set of rules for my UserSettingController.

### What happened:
The store and update method in the controller have invalid request type when I try to pass on my UserSettingRequest instead of a SettingRequest.

### What Should I Do:
I'm wondering if there is a way to do what I'm trying to accomplish here!

### Backpack, Laravel, PHP, DB version:
Laravel 5.7
PHP 7.2.20

**Comment by tabacitu** [comment]
Hi @3Flag ,

Yes there is. Sounds like you've hit into a PHP limitation - you can only typehint class loaded in THAT controller. Make sure you have ```use``` statements for the requests at the top of _your_ SettingCrudController. It's not enough that they're in the SettingCrudController you extended.

If this doesn't work either (or even if it does), consider copying SettingsManager's basic files (controller, request, route) into your app, and uninstalling SettingsManager. If you overwrite the two methods it provides... I think it's better to drop the dependency altogether.

Hope it helps.
Cheers!
