### ISSUE TITLE
Laravel Setting is not working (not saving)

### ISSUE THREAD

**Issue by raulsh** [Laravel-Backpack/Settings#86]
# Bug report
Not saving

### What I did:
I tried to save a setting the setting was not saved

### What I expected to happen:
Save the setting

### What happened:
Not saved in the database.

### What I've already tried to fix it:
Nothing

### Backpack, Laravel, PHP, DB version:
Backpack 4.0, Laravel 6.0.3, PHP 7.3.7, MariaDB 10.3.16

**Comment by tabacitu** [comment]
Oups - you're totally right. Thank you for raising the issue @raulsh ! I've just pushed the fix, you can get it with ```composer update```. Cheers!
