### ISSUE TITLE
Add Setting button is missing

### ISSUE THREAD

**Issue by ikkebra** [Laravel-Backpack/Settings#89]
# Bug report
The [ +Add Setting] button is not showing up when I go to Settings (admin/setting)

### What I did:
Fresh install of the latest Laravel followed by installing Backpack and backpack-settings

### What I expected to happen:
To see the Add Setting button in the index view

### What happened:
The create button is not there.

### Backpack, Laravel, PHP, DB version:
backpack crud 4.0.23, laravel 6.6.2, php 7.3.11, mariadb 10.3.16

**Comment by ikkebra** [comment]
![Screen Shot 2019-12-05 at 11 11 40 AM](https://user-images.githubusercontent.com/106914/70271452-a5422c80-1763-11ea-8e3a-9a43aed862f5.png)

**Comment by ikkebra** [comment]
Nevermind, just saw that there is no interface to add settings, which makes perfect sense now that I think about it and after I read all the docs!

**Comment by tabacitu** [comment]
No problem. Indeed - it was a design choice. It was said somewhere else, but let me answer here too: it doesn't really make sense to let admins Add settings, when they can't Use those settings (they don't have access to change blade files, controllers, models, etc).

Cheers!
